/* PLOP_INJECT_IMPORT */
export { PageFooter } from './page-footer'
export { HeaderBlock } from './header-block'
export { ZerosBlock } from './zeros-block'
export { EightiesBlock } from './eighties-block'
export { SixtiesBlock } from './sixties-block'
export { Header } from './header'
export { Footer } from './footer'
export { Slider } from './slider'
export { PeriodInfo } from './period-info'
export { YearInfo } from './year-info'
export * from './paints'
export { Promo } from './promo'
export { Integration } from './integration'
